### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by Kern046**
This pull request is a suggestion to improve the creation of database config.

Instead of create the config in a GUI, this code replaces the current install.php with a CLI script.

I think it will be more secure and proper !

It is just a suggestion, I will be glad to discuss it with you :).

### CODE REVIEW

**Comment by jburns131** [comment]
@Kern046,

First of all, thank you for your contribution and interest!

Please follow Issue #58.

Thanks!

**Comment by muka** [comment]
Seems that @Kern046 has done an excellent work in his fork, making the project namespaced and unit-tested. 

Would you consider to merge it in the near future?

Thanks

**Comment by abiusx** [comment]
Jesse has taken over this. @jburns31 if you don’t want to handle this let me know so that I can take over.

**Comment by Kern046** [comment]
Hello ! Thank you muka :) ! There's still a lot of work ! I'm working on the branch "style-issues" in my repository, trying to get better performances and clean the code with tools as Scrutinizer and Blackfire. I'm still working on it, although I have few time. I think that in few days, I will be able to create a nice Pull Request, with a refactored nested set and cleaner managers :) !

It also solves the database connection problem, the connection will be sent to PHP-RBAC by the user, and not by the library itself.

**Comment by muka** [comment]
@Kern046 thank you for the update. I like the connection solution. 

I'm looking to use it in a Symfony based project with Doctrine as ORM. 
Would be nice to have some interfaces and abstract objects to deal with Permission, Role and User for best interoperability. 
I'll give it a try and will report back. 

Thank you all
Best

**Comment by Kern046** [comment]
If it mights interest you, I also developed a RBAC-bundle at work. Till now it is on our own gitlab, by I can ask to put it on github, I think it shall help.

We add the notion of context, to give a global permission on a defined set of objects. (For example, A user is a forum moderator, but without the contexts, you need more logic in you want the user to be moderator on a restricted set of rubrics. With contexts, you can tell your program "This user has the permission moderate_rubric on the rubrics 12, 17 and 21"

**Comment by muka** [comment]
Would be great for sure! I'd be happy to take a look and contribute instead of writing it from scratch

**Comment by abiusx** [comment]
It is interesting. How did you implement this?

---

Notice: This message is digitally signed, its source and integrity are verifiable.
If you mail client does not support S/MIME verification, it will display a file (smime.p7s), which includes the X.509 certificate and the signature body.  Read more at Certified E-Mail with Comodo and Thunderbird http://abiusx.com/certified-e-mail-with-comodo-and-thunderbird/ in AbiusX.com

**Comment by jburns131** [comment]
Hello everyone, I am well and still very much alive :-)

Between dealing with meat-space bug reports and debugging marathons, along with feeling a tad bit of digital burnout I had to pull back and invest more time away from a keyboard than I had planned.

I have not been able to look at the code, but this does sound very interesting. Can't wait to see what adjustments you  made to the nested sets @Kern046.

@Kern046: I'd love to get together on skype or g+ hangout and touch base. Feel free to contact me on google or skype: jburns131

**Comment by Kern046** [comment]
Yeah, without problems, I added you !

Another thing that I will develop later, better Unit Tests, with mocks and tests of the nested set itself.

For the Bundle, my lead-dev wants it to be upgraded with the improved version of RBAC before setting it public ! He also want it to support Propel, currently it only supports Doctrine !

For the implementation of the contexts, we have a little tinkered that binds in a table the permission id, the user id, the name of the context (in the previous example : "rubric") and the id of the context.

I want to work on a better implementation, because I fear that this way of doing things will result in a huge table with thousands entries for a few set of users. For the users which have permissions on ALL the rubrics, this feature shouldn't be used.

**Comment by abiusx** [comment]
This is an important discussion we’ve had several times. The current RBAC is there to support function-level access control.
One use can either do something, or not. For data level access control, we need one record per record of data to fine-grain data access. This is currently not supported by the library, as adding and modifying permissions and roles are two orders of magnitude slower than querying them (which is the fundamental feature of the library and everything is built around that).

If there is a limited number of data records, it can be easily embedded in this model, e.g if we want to give state-based permissions, we can just add all 50 states to the system and then assign it to the designated user.

One more thing worthy of improvement is the “any” query. For example, sometimes we’d like to know if a user has “any” of the following 25 permissions, and if s/he does, we want to show some button on the UI and otherwise not. Having a loop and querying the RBAC system 25 times isn’t the wisest way to do this and atm it is on the business logic of the system to handle that. Any idaes of improvement on that would be golden!

---

Notice: This message is digitally signed, its source and integrity are verifiable.
If you mail client does not support S/MIME verification, it will display a file (smime.p7s), which includes the X.509 certificate and the signature body.  Read more at Certified E-Mail with Comodo and Thunderbird http://abiusx.com/certified-e-mail-with-comodo-and-thunderbird/ in AbiusX.com

**Comment by Kern046** [comment]
Yeah, that's why I didn't implement it in the library, I did in the bundle ! This bundle was originally a dependency of a commercial project, with problematics about big number of different permissions and a necessary granularity due to cataclysmic specifications ! We give the possibility to use this feature, or not :) !

But nothing of this is implemented in the original library !

About your last point, I think I can easily add it in SQL, with a WHERE .... IN statement !

**Comment by abiusx** [comment]
Lets create a new issue (or page) in Github repo, where users can post their use-case scenarios. This will really help devs in development and testing. This library is big and can have multiple different usecases, and every dev just considers the one s/he’s focused on when working.

About the idea for “any” lookup, that is golden, unless those permissions are not all descendants of one node. There should be a way to do it all in one query, asking the user for the list of perms. It is still a good idea though, and I’d appreciate it if you added it to the issues list on your own name.
-A

---

Notice: This message is digitally signed, its source and integrity are verifiable.
If you mail client does not support S/MIME verification, it will display a file (smime.p7s), which includes the X.509 certificate and the signature body.  Read more at Certified E-Mail with Comodo and Thunderbird http://abiusx.com/certified-e-mail-with-comodo-and-thunderbird/ in AbiusX.com

**Comment by Kern046** [comment]
Agree with that !

**Pull request closed without merging**
