### PR TITLE
Style issues

### PR DESCRIPTION
**Pull request by Kern046**

### CODE REVIEW

**Comment by abiusx** [comment]
these changes look incredible.
Lets see whether Jesse wants to review and merge them, or I should do that?
@jburns131

---

Notice: This message is digitally signed, its source and integrity are verifiable.
If you mail client does not support S/MIME verification, it will display a file (smime.p7s), which includes the X.509 certificate and the signature body.  Read more at Certified E-Mail with Comodo and Thunderbird http://abiusx.com/certified-e-mail-with-comodo-and-thunderbird/ in AbiusX.com http://abiusx.com/

**Comment by Kern046** [comment]
I closed it because I did a mistake when I created my pull request ! I would be glad to contribute to the library, but there's still a lot of work to do to make it perfect :) ! I let you judge if you want to merge this in its state or wait for the next optimizations !

I give you some links : 

Blackfire is a SensioLabs profiler, I made a comparison between the original version and this one : 
https://blackfire.io/profiles/compare/aade8c7c-3a26-46e5-b1b3-a97927fa265f/graph
If you put your mouse over the stats above, you will have the percent of evolution.

Scrutinizer is a code-quality inspector, which analyses the code and note it, function after function. The original note wasn't bad, and as you can see, there's still a lot to do on that matter !
https://scrutinizer-ci.com/g/Kern046/rbac/

**Comment by abiusx** [comment]
I can see the profiling, but not the comparison.
Also, what code did you use to profile this?

Many of the problems reported by Scrutinizer are not problems at all. I don’t know what it exactly is based on, but sounds proprietary to me.
 e.g:
eturn ($count == 0) ? null : $output;
Bug Best Practice introduced 18 days ago by   https://github.com/scrutinizer-ci/php-analyzer/issues/new?body=%body% https://scrutinizer-ci.com/github-login?scope=public_repo  https://scrutinizer-ci.com/github-login?target_path=https%3A%2F%2Fscrutinizer-ci.com%2Fg%2FKern046%2Frbac%2Fissues%2Fmaster%2Ffiles%2Fsrc%2FPhpRbac%2FDatabase%2FDatabaseManager.php%3Forder%3Dasc%26orderField%3Dpath
 https://scrutinizer-ci.com/g/Kern046/rbac/issues/master/files/src/PhpRbac/Database/DatabaseManager.php?orderField=path&order=asc#The return type of return $count == 0 ? null : $output; (array) is incompatible with the return type documented by PhpRbac\Database\DatabaseManager::mysqliRequest of type boolean.

The funcion documentation says it returns null or array, but it expects something else.
-A

**Comment by Kern046** [comment]
Here is the comparison, strange that you can't see it, as it is public shared !
blackfire_profile

Some of the scrutinizer issues are indeed due to the function documentation and aren't so bad, but there is a lot of duplication issues, that can be easily avoided :) ! I'm working on that !

Scrutinizer also wants the object methods to be short with few complexity, and put bad notes on functions which have too many nested levels.

**Comment by abiusx** [comment]
I can see the image, but can’t make sense of it!
Can you give me an example of scrutinizers work?

**Comment by Kern046** [comment]
It is saying :

Execution time is 84% faster (-1.49s)
I/O streams are 93% faster (-1.03s)
CPU time is 69% faster (-452ms)
Memory usage is 33.7% bigger (+236KB), the only bad point of these changes !

Here comes scrutinizer : 
scrutinizer_example

In this example, Scrutinizer has found a duplication of the code and thinks that we can factor it in a new function. It gives advices to make the cde easier to read and more performant. It is also able to find bugs, but there is no bugs for the moment in the library :).

**Comment by abiusx** [comment]
Scrutinizer sounds useful (at least in some cases). We’ve actually found a couple bugs, but they are not found by automated tools as they are inside strings.
As for the profiling, what code is being executed to generate this profile?

**Comment by Kern046** [comment]
I used the code proposed by another user in issue #55 ! I changed it to fit the new calls. The current file is : https://github.com/Kern046/rbac/blob/style-issues/index.php

**Comment by abiusx** [comment]
Ok now it makes sense.
The RBAC library’s focus is on high performance lookups, not inserts and updates. They are actually expected to be slow and non-frequent. Make a benchmark on RBAC::Check using a moderately complex tree and see how different it works.
-A

**Pull request closed without merging**
